apiVersion: v1
kind: Service
metadata:
  name: simple-k8s-example-service
spec:
  selector:
    app: simple-k8s-example # specifies which pods to forward requests to
  ports:
  - port: 80
    targetPort: 9698
