apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-clothing-model-deployment
spec:
  selector:
    matchLabels:
      app: gateway-clothing-model
  template:
    metadata:
      labels:
        app: gateway-clothing-model
    spec:
      containers:
      - name: gateway-clothing-model
        image: similoluwaokunowo/mlzoomcamp-10-gateway:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 9696
        env:
          - name: TF_SERVING_HOST 
            value: tf-serving-clothing-model-service.default.svc.cluster.local:8500
